/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommentOnGagneDeLArgentRouteImport } from './routes/comment-on-gagne-de-l-argent'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ModeBudgetRouteImport } from './routes/mode-budget'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as ConseilsIndexRouteImport } from './routes/conseils.index'
import { Route as ConseilsSlugRouteImport } from './routes/conseils.$slug'
import { Route as VolsPasChersSlugRouteImport } from './routes/vols-pas-chers.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentOnGagneDeLArgentRoute = CommentOnGagneDeLArgentRouteImport.update({
  id: '/comment-on-gagne-de-l-argent',
  path: '/comment-on-gagne-de-l-argent',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeBudgetRoute = ModeBudgetRouteImport.update({
  id: '/mode-budget',
  path: '/mode-budget',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseilsIndexRoute = ConseilsIndexRouteImport.update({
  id: '/conseils/',
  path: '/conseils/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseilsSlugRoute = ConseilsSlugRouteImport.update({
  id: '/conseils/$slug',
  path: '/conseils/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VolsPasChersSlugRoute = VolsPasChersSlugRouteImport.update({
  id: '/vols-pas-chers/$slug',
  path: '/vols-pas-chers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comment-on-gagne-de-l-argent': typeof CommentOnGagneDeLArgentRoute
  '/faq': typeof FaqRoute
  '/mode-budget': typeof ModeBudgetRoute
  '/recherche': typeof RechercheRoute
  '/conseils/$slug': typeof ConseilsSlugRoute
  '/vols-pas-chers/$slug': typeof VolsPasChersSlugRoute
  '/conseils/': typeof ConseilsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comment-on-gagne-de-l-argent': typeof CommentOnGagneDeLArgentRoute
  '/faq': typeof FaqRoute
  '/mode-budget': typeof ModeBudgetRoute
  '/recherche': typeof RechercheRoute
  '/conseils/$slug': typeof ConseilsSlugRoute
  '/vols-pas-chers/$slug': typeof VolsPasChersSlugRoute
  '/conseils': typeof ConseilsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comment-on-gagne-de-l-argent': typeof CommentOnGagneDeLArgentRoute
  '/faq': typeof FaqRoute
  '/mode-budget': typeof ModeBudgetRoute
  '/recherche': typeof RechercheRoute
  '/conseils/$slug': typeof ConseilsSlugRoute
  '/vols-pas-chers/$slug': typeof VolsPasChersSlugRoute
  '/conseils/': typeof ConseilsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comment-on-gagne-de-l-argent'
    | '/faq'
    | '/mode-budget'
    | '/recherche'
    | '/conseils/$slug'
    | '/vols-pas-chers/$slug'
    | '/conseils/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comment-on-gagne-de-l-argent'
    | '/faq'
    | '/mode-budget'
    | '/recherche'
    | '/conseils/$slug'
    | '/vols-pas-chers/$slug'
    | '/conseils'
  id:
    | '__root__'
    | '/'
    | '/comment-on-gagne-de-l-argent'
    | '/faq'
    | '/mode-budget'
    | '/recherche'
    | '/conseils/$slug'
    | '/vols-pas-chers/$slug'
    | '/conseils/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommentOnGagneDeLArgentRoute: typeof CommentOnGagneDeLArgentRoute
  FaqRoute: typeof FaqRoute
  ModeBudgetRoute: typeof ModeBudgetRoute
  RechercheRoute: typeof RechercheRoute
  ConseilsSlugRoute: typeof ConseilsSlugRoute
  VolsPasChersSlugRoute: typeof VolsPasChersSlugRoute
  ConseilsIndexRoute: typeof ConseilsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-on-gagne-de-l-argent': {
      id: '/comment-on-gagne-de-l-argent'
      path: '/comment-on-gagne-de-l-argent'
      fullPath: '/comment-on-gagne-de-l-argent'
      preLoaderRoute: typeof CommentOnGagneDeLArgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mode-budget': {
      id: '/mode-budget'
      path: '/mode-budget'
      fullPath: '/mode-budget'
      preLoaderRoute: typeof ModeBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils/': {
      id: '/conseils/'
      path: '/conseils'
      fullPath: '/conseils/'
      preLoaderRoute: typeof ConseilsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils/$slug': {
      id: '/conseils/$slug'
      path: '/conseils/$slug'
      fullPath: '/conseils/$slug'
      preLoaderRoute: typeof ConseilsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vols-pas-chers/$slug': {
      id: '/vols-pas-chers/$slug'
      path: '/vols-pas-chers/$slug'
      fullPath: '/vols-pas-chers/$slug'
      preLoaderRoute: typeof VolsPasChersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommentOnGagneDeLArgentRoute: CommentOnGagneDeLArgentRoute,
  FaqRoute: FaqRoute,
  ModeBudgetRoute: ModeBudgetRoute,
  RechercheRoute: RechercheRoute,
  ConseilsSlugRoute: ConseilsSlugRoute,
  VolsPasChersSlugRoute: VolsPasChersSlugRoute,
  ConseilsIndexRoute: ConseilsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
