/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HebergementRouteImport } from './routes/hebergement'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ModeBudgetRouteImport } from './routes/mode-budget'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminJournalRouteImport } from './routes/admin.journal'
import { Route as AlertesDesinscriptionRouteImport } from './routes/alertes.desinscription'
import { Route as ConseilsIndexRouteImport } from './routes/conseils.index'
import { Route as ConseilsSlugRouteImport } from './routes/conseils.$slug'
import { Route as SitemapVolsPageDotxmlRouteImport } from './routes/sitemap-vols.$page[.]xml'
import { Route as VolsPasChersSlugRouteImport } from './routes/vols-pas-chers.$slug'
import { Route as VolsSlugRouteImport } from './routes/vols.$slug'
import { Route as ApiPublicVerifierAlertesRouteImport } from './routes/api/public/verifier-alertes'
import { Route as ConseilsDestinationsIndexRouteImport } from './routes/conseils.destinations.index'
import { Route as ConseilsDestinationsCityRouteImport } from './routes/conseils.destinations.$city'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HebergementRoute = HebergementRouteImport.update({
  id: '/hebergement',
  path: '/hebergement',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeBudgetRoute = ModeBudgetRouteImport.update({
  id: '/mode-budget',
  path: '/mode-budget',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJournalRoute = AdminJournalRouteImport.update({
  id: '/admin/journal',
  path: '/admin/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertesDesinscriptionRoute = AlertesDesinscriptionRouteImport.update({
  id: '/alertes/desinscription',
  path: '/alertes/desinscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseilsIndexRoute = ConseilsIndexRouteImport.update({
  id: '/conseils/',
  path: '/conseils/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseilsSlugRoute = ConseilsSlugRouteImport.update({
  id: '/conseils/$slug',
  path: '/conseils/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapVolsPageDotxmlRoute = SitemapVolsPageDotxmlRouteImport.update({
  id: '/sitemap-vols/$page.xml',
  path: '/sitemap-vols/$page.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VolsPasChersSlugRoute = VolsPasChersSlugRouteImport.update({
  id: '/vols-pas-chers/$slug',
  path: '/vols-pas-chers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VolsSlugRoute = VolsSlugRouteImport.update({
  id: '/vols/$slug',
  path: '/vols/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifierAlertesRoute =
  ApiPublicVerifierAlertesRouteImport.update({
    id: '/api/public/verifier-alertes',
    path: '/api/public/verifier-alertes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConseilsDestinationsIndexRoute =
  ConseilsDestinationsIndexRouteImport.update({
    id: '/conseils/destinations/',
    path: '/conseils/destinations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConseilsDestinationsCityRoute =
  ConseilsDestinationsCityRouteImport.update({
    id: '/conseils/destinations/$city',
    path: '/conseils/destinations/$city',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/hebergement': typeof HebergementRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mode-budget': typeof ModeBudgetRoute
  '/recherche': typeof RechercheRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/journal': typeof AdminJournalRoute
  '/alertes/desinscription': typeof AlertesDesinscriptionRoute
  '/conseils/$slug': typeof ConseilsSlugRoute
  '/sitemap-vols/$page.xml': typeof SitemapVolsPageDotxmlRoute
  '/vols-pas-chers/$slug': typeof VolsPasChersSlugRoute
  '/vols/$slug': typeof VolsSlugRoute
  '/conseils/': typeof ConseilsIndexRoute
  '/api/public/verifier-alertes': typeof ApiPublicVerifierAlertesRoute
  '/conseils/destinations/$city': typeof ConseilsDestinationsCityRoute
  '/conseils/destinations/': typeof ConseilsDestinationsIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/hebergement': typeof HebergementRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mode-budget': typeof ModeBudgetRoute
  '/recherche': typeof RechercheRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/journal': typeof AdminJournalRoute
  '/alertes/desinscription': typeof AlertesDesinscriptionRoute
  '/conseils/$slug': typeof ConseilsSlugRoute
  '/sitemap-vols/$page.xml': typeof SitemapVolsPageDotxmlRoute
  '/vols-pas-chers/$slug': typeof VolsPasChersSlugRoute
  '/vols/$slug': typeof VolsSlugRoute
  '/conseils': typeof ConseilsIndexRoute
  '/api/public/verifier-alertes': typeof ApiPublicVerifierAlertesRoute
  '/conseils/destinations/$city': typeof ConseilsDestinationsCityRoute
  '/conseils/destinations': typeof ConseilsDestinationsIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/hebergement': typeof HebergementRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mode-budget': typeof ModeBudgetRoute
  '/recherche': typeof RechercheRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/journal': typeof AdminJournalRoute
  '/alertes/desinscription': typeof AlertesDesinscriptionRoute
  '/conseils/$slug': typeof ConseilsSlugRoute
  '/sitemap-vols/$page.xml': typeof SitemapVolsPageDotxmlRoute
  '/vols-pas-chers/$slug': typeof VolsPasChersSlugRoute
  '/vols/$slug': typeof VolsSlugRoute
  '/conseils/': typeof ConseilsIndexRoute
  '/api/public/verifier-alertes': typeof ApiPublicVerifierAlertesRoute
  '/conseils/destinations/$city': typeof ConseilsDestinationsCityRoute
  '/conseils/destinations/': typeof ConseilsDestinationsIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cgu'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/hebergement'
    | '/mentions-legales'
    | '/mode-budget'
    | '/recherche'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/admin/journal'
    | '/alertes/desinscription'
    | '/conseils/$slug'
    | '/sitemap-vols/$page.xml'
    | '/vols-pas-chers/$slug'
    | '/vols/$slug'
    | '/conseils/'
    | '/api/public/verifier-alertes'
    | '/conseils/destinations/$city'
    | '/conseils/destinations/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgu'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/hebergement'
    | '/mentions-legales'
    | '/mode-budget'
    | '/recherche'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/admin/journal'
    | '/alertes/desinscription'
    | '/conseils/$slug'
    | '/sitemap-vols/$page.xml'
    | '/vols-pas-chers/$slug'
    | '/vols/$slug'
    | '/conseils'
    | '/api/public/verifier-alertes'
    | '/conseils/destinations/$city'
    | '/conseils/destinations'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/cgu'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/hebergement'
    | '/mentions-legales'
    | '/mode-budget'
    | '/recherche'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/admin/journal'
    | '/alertes/desinscription'
    | '/conseils/$slug'
    | '/sitemap-vols/$page.xml'
    | '/vols-pas-chers/$slug'
    | '/vols/$slug'
    | '/conseils/'
    | '/api/public/verifier-alertes'
    | '/conseils/destinations/$city'
    | '/conseils/destinations/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CguRoute: typeof CguRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  HebergementRoute: typeof HebergementRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ModeBudgetRoute: typeof ModeBudgetRoute
  RechercheRoute: typeof RechercheRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminJournalRoute: typeof AdminJournalRoute
  AlertesDesinscriptionRoute: typeof AlertesDesinscriptionRoute
  ConseilsSlugRoute: typeof ConseilsSlugRoute
  SitemapVolsPageDotxmlRoute: typeof SitemapVolsPageDotxmlRoute
  VolsPasChersSlugRoute: typeof VolsPasChersSlugRoute
  VolsSlugRoute: typeof VolsSlugRoute
  ConseilsIndexRoute: typeof ConseilsIndexRoute
  ApiPublicVerifierAlertesRoute: typeof ApiPublicVerifierAlertesRoute
  ConseilsDestinationsCityRoute: typeof ConseilsDestinationsCityRoute
  ConseilsDestinationsIndexRoute: typeof ConseilsDestinationsIndexRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hebergement': {
      id: '/hebergement'
      path: '/hebergement'
      fullPath: '/hebergement'
      preLoaderRoute: typeof HebergementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mode-budget': {
      id: '/mode-budget'
      path: '/mode-budget'
      fullPath: '/mode-budget'
      preLoaderRoute: typeof ModeBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/journal': {
      id: '/admin/journal'
      path: '/admin/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AdminJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertes/desinscription': {
      id: '/alertes/desinscription'
      path: '/alertes/desinscription'
      fullPath: '/alertes/desinscription'
      preLoaderRoute: typeof AlertesDesinscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils/': {
      id: '/conseils/'
      path: '/conseils'
      fullPath: '/conseils/'
      preLoaderRoute: typeof ConseilsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils/$slug': {
      id: '/conseils/$slug'
      path: '/conseils/$slug'
      fullPath: '/conseils/$slug'
      preLoaderRoute: typeof ConseilsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-vols/$page.xml': {
      id: '/sitemap-vols/$page.xml'
      path: '/sitemap-vols/$page.xml'
      fullPath: '/sitemap-vols/$page.xml'
      preLoaderRoute: typeof SitemapVolsPageDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vols-pas-chers/$slug': {
      id: '/vols-pas-chers/$slug'
      path: '/vols-pas-chers/$slug'
      fullPath: '/vols-pas-chers/$slug'
      preLoaderRoute: typeof VolsPasChersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vols/$slug': {
      id: '/vols/$slug'
      path: '/vols/$slug'
      fullPath: '/vols/$slug'
      preLoaderRoute: typeof VolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verifier-alertes': {
      id: '/api/public/verifier-alertes'
      path: '/api/public/verifier-alertes'
      fullPath: '/api/public/verifier-alertes'
      preLoaderRoute: typeof ApiPublicVerifierAlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils/destinations/': {
      id: '/conseils/destinations/'
      path: '/conseils/destinations'
      fullPath: '/conseils/destinations/'
      preLoaderRoute: typeof ConseilsDestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils/destinations/$city': {
      id: '/conseils/destinations/$city'
      path: '/conseils/destinations/$city'
      fullPath: '/conseils/destinations/$city'
      preLoaderRoute: typeof ConseilsDestinationsCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CguRoute: CguRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  HebergementRoute: HebergementRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ModeBudgetRoute: ModeBudgetRoute,
  RechercheRoute: RechercheRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminJournalRoute: AdminJournalRoute,
  AlertesDesinscriptionRoute: AlertesDesinscriptionRoute,
  ConseilsSlugRoute: ConseilsSlugRoute,
  SitemapVolsPageDotxmlRoute: SitemapVolsPageDotxmlRoute,
  VolsPasChersSlugRoute: VolsPasChersSlugRoute,
  VolsSlugRoute: VolsSlugRoute,
  ConseilsIndexRoute: ConseilsIndexRoute,
  ApiPublicVerifierAlertesRoute: ApiPublicVerifierAlertesRoute,
  ConseilsDestinationsCityRoute: ConseilsDestinationsCityRoute,
  ConseilsDestinationsIndexRoute: ConseilsDestinationsIndexRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
