/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModeBudgetRouteImport } from './routes/mode-budget'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as VolsPasChersSlugRouteImport } from './routes/vols-pas-chers.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeBudgetRoute = ModeBudgetRouteImport.update({
  id: '/mode-budget',
  path: '/mode-budget',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const VolsPasChersSlugRoute = VolsPasChersSlugRouteImport.update({
  id: '/vols-pas-chers/$slug',
  path: '/vols-pas-chers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mode-budget': typeof ModeBudgetRoute
  '/recherche': typeof RechercheRoute
  '/vols-pas-chers/$slug': typeof VolsPasChersSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mode-budget': typeof ModeBudgetRoute
  '/recherche': typeof RechercheRoute
  '/vols-pas-chers/$slug': typeof VolsPasChersSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mode-budget': typeof ModeBudgetRoute
  '/recherche': typeof RechercheRoute
  '/vols-pas-chers/$slug': typeof VolsPasChersSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mode-budget' | '/recherche' | '/vols-pas-chers/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mode-budget' | '/recherche' | '/vols-pas-chers/$slug'
  id: '__root__' | '/' | '/mode-budget' | '/recherche' | '/vols-pas-chers/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModeBudgetRoute: typeof ModeBudgetRoute
  RechercheRoute: typeof RechercheRoute
  VolsPasChersSlugRoute: typeof VolsPasChersSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mode-budget': {
      id: '/mode-budget'
      path: '/mode-budget'
      fullPath: '/mode-budget'
      preLoaderRoute: typeof ModeBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vols-pas-chers/$slug': {
      id: '/vols-pas-chers/$slug'
      path: '/vols-pas-chers/$slug'
      fullPath: '/vols-pas-chers/$slug'
      preLoaderRoute: typeof VolsPasChersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModeBudgetRoute: ModeBudgetRoute,
  RechercheRoute: RechercheRoute,
  VolsPasChersSlugRoute: VolsPasChersSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
